language: elixir
sudo: false
matrix:
  include:
    - elixir:  1.8
      otp_release: 21.3
    - elixir:  1.7
      otp_release: 21.3
services:
  - rabbitmq
script:
  - mix credo --strict
  - mix test